// Code generated by "stringer -type=ValidationResult -output=generated_string.go"; DO NOT EDIT.

package phonenumbers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IS_POSSIBLE-0]
	_ = x[INVALID_COUNTRY_CODE-1]
	_ = x[TOO_SHORT-2]
	_ = x[TOO_LONG-3]
	_ = x[IS_POSSIBLE_LOCAL_ONLY-4]
	_ = x[INVALID_LENGTH-5]
}

const _ValidationResult_name = "IS_POSSIBLEINVALID_COUNTRY_CODETOO_SHORTTOO_LONGIS_POSSIBLE_LOCAL_ONLYINVALID_LENGTH"

var _ValidationResult_index = [...]uint8{0, 11, 31, 40, 48, 70, 84}

func (i ValidationResult) String() string {
	if i < 0 || i >= ValidationResult(len(_ValidationResult_index)-1) {
		return "ValidationResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValidationResult_name[_ValidationResult_index[i]:_ValidationResult_index[i+1]]
}
