// Code generated by cmd/buildmetadata. DO NOT EDIT.

package phonenumbers

// MetadataVersion is the upstream libphonenumber release tag that the embedded
// metadata under data/ was built from.
const MetadataVersion = "v9.0.31"
